force-app/main/default/objects/Approval_Process_Template__c/Approval_Process_Template__c.object-meta.xml
<CustomObject>
    <label>Approval Process Template</label>
    <nameField>
        <label>Approval Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Process_Template__c/fields/Entry_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria__c</fullName>
    <label>Entry Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Action__c/Approval_Process_Template_Action__c.object-meta.xml
<CustomObject>
    <label>Approval Process Template Action</label>
    <nameField>
        <displayFormat>APTA-{0000}</displayFormat>
        <label>Approval Process Template Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Process Template Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Process_Template_Action__c/fields/Approval_Process_Template__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Template__c</fullName>
    <label>Approval Process Template</label>
    <referenceTo>Approval_Process_Template__c</referenceTo>
    <relationshipLabel>Approval Process Template Actions</relationshipLabel>
    <relationshipName>Approval_Process_Template_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Action__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Step__c/Approval_Process_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Approval Process Template Step</label>
    <nameField>
        <displayFormat>APTS-{0000}</displayFormat>
        <label>Approval Process Template Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Process Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Process_Template_Step__c/fields/Approval_Process_Template__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Template__c</fullName>
    <label>Approval Process Template</label>
    <referenceTo>Approval_Process_Template__c</referenceTo>
    <relationshipLabel>Approval Process Template Steps</relationshipLabel>
    <relationshipName>Approval_Process_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Step__c/fields/Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Member_Id__c</fullName>
    <label>Member Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Step__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalProcessTemplateRepoTest.cls
@IsTest
class ApprovalProcessTemplateRepoTest {
	@IsTest
	static void testApprovalProcessTemplateRepo() {
		System.runAs(new User(Id = UserInfo.getUserId())) {
			Approval_Process_Template__c template = new Approval_Process_Template__c();
			template.Name = 'Test Approval Process';
			template.Object_Type__c = 'Account';
			template.Entry_Criteria__c = 'CONTAINS(Name, \'test\')';

			insert template;

			Approval_Process_Template_Step__c templateStep = new Approval_Process_Template_Step__c();
			templateStep.Approval_Process_Template__c = template.Id;
			templateStep.Order__c = 1;
			templateStep.Type__c = 'User';
			templateStep.Member_Id__c = UserInfo.getUserId();

			insert templateStep;

			Approval_Process_Template_Action__c templateAction = new Approval_Process_Template_Action__c();
			templateAction.Approval_Process_Template__c = template.Id;
			templateAction.Order__c = 1;
			templateAction.Type__c = 'Update';
			templateAction.Is_Approved_Action__c = true;
			templateAction.Action_JSON__c = '{"description": "Approved"}';

			insert templateAction;

			Test.startTest();

			ApprovalProcessTemplateRepository repo = new ApprovalProcessTemplateRepositoryImpl();

			List<ApprovalProcessTemplate> accountTemplates = repo.listByObjectName('Account');
			List<ApprovalProcessTemplate> opportunityTemplates = repo.listByObjectName(
				'Opportunity'
			);

			Test.stopTest();

			Assert.isTrue(accountTemplates.size() > 0);
			Assert.isTrue(opportunityTemplates.size() == 0);
		}
	}
}