force-app/main/default/objects/Approval_Process_Template__c/Approval_Process_Template__c.object-meta.xml
<CustomObject>
    <label>Approval Process Template</label>
    <nameField>
        <label>Approval Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Process_Template__c/fields/Entry_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria__c</fullName>
    <label>Entry Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Action__c/Approval_Process_Template_Action__c.object-meta.xml
<CustomObject>
    <label>Approval Process Template Action</label>
    <nameField>
        <displayFormat>APTA-{0000}</displayFormat>
        <label>Approval Process Template Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Process Template Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Process_Template_Action__c/fields/Approval_Process_Template__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Template__c</fullName>
    <label>Approval Process Template</label>
    <referenceTo>Approval_Process_Template__c</referenceTo>
    <relationshipLabel>Approval Process Template Actions</relationshipLabel>
    <relationshipName>Approval_Process_Template_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Action__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Step__c/Approval_Process_Template_Step__c.object-meta.xml
<CustomObject>
    <label>Approval Process Template Step</label>
    <nameField>
        <displayFormat>APTS-{0000}</displayFormat>
        <label>Approval Process Template Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Process Template Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Process_Template_Step__c/fields/Approval_Process_Template__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Template__c</fullName>
    <label>Approval Process Template</label>
    <referenceTo>Approval_Process_Template__c</referenceTo>
    <relationshipLabel>Approval Process Template Steps</relationshipLabel>
    <relationshipName>Approval_Process_Template_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Step__c/fields/Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Member_Id__c</fullName>
    <label>Member Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Template_Step__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalProcessTemplateRepositoryImpl.cls
public inherited sharing class ApprovalProcessTemplateRepositoryImpl implements ApprovalProcessTemplateRepository {
	public List<ApprovalProcessTemplate> listByObjectName(String objectName) {
		List<ApprovalProcessTemplate> approvalProcessTemplates = new List<ApprovalProcessTemplate>();

		List<Approval_Process_Template__c> templateSObjects = [
			SELECT
				Id,
				Name,
				Entry_Criteria__c,
				Object_Type__c,
				(
					SELECT Id, Order__c, Type__c, Member_Id__c
					FROM Approval_Process_Template_Steps__r
				),
				(
					SELECT Id, Order__c, Type__c, Is_Approved_Action__c, Action_JSON__c
					FROM Approval_Process_Template_Actions__r
				)
			FROM Approval_Process_Template__c
			WHERE Object_Type__c = :objectName
		];

		for (Approval_Process_Template__c templateSObject : templateSObjects) {
			approvalProcessTemplates.add(this.createTemplateFromSObject(templateSObject));
		}

		return approvalProcessTemplates;
	}

	private ApprovalProcessTemplate createTemplateFromSObject(
		Approval_Process_Template__c templateSObject
	) {
		ApprovalProcessTemplate template = new ApprovalProcessTemplate();

		template.setId(templateSObject.Id);
		template.setName(templateSObject.Name);
		template.setObjectType(templateSObject.Object_Type__c);
		template.setEntryCriteria(templateSObject.Entry_Criteria__c);

		for (
			Approval_Process_Template_Step__c templateStepSObject : templateSObject.Approval_Process_Template_Steps__r
		) {
			template.addStep(this.createTemplateStepFromSObject(templateStepSObject));
		}

		for (
			Approval_Process_Template_Action__c templateActionSObject : templateSObject.Approval_Process_Template_Actions__r
		) {
			template.addAction(this.createTemplateActionFromSObject(templateActionSObject));
		}

		return template;
	}

	private ApprovalProcessTemplateStep createTemplateStepFromSObject(
		Approval_Process_Template_Step__c templateStepSObject
	) {
		ApprovalProcessTemplateStep templateStep = new ApprovalProcessTemplateStep();

		templateStep.setId(templateStepSObject.Id);
		templateStep.setOrder((Integer) templateStepSObject.Order__c);
		templateStep.setType(templateStepSObject.Type__c);
		templateStep.setMemberId(templateStepSObject.Member_Id__c);

		return templateStep;
	}

	private ApprovalProcessTemplateAction createTemplateActionFromSObject(
		Approval_Process_Template_Action__c templateActionSObject
	) {
		ApprovalProcessTemplateAction templateAction = new ApprovalProcessTemplateAction();

		templateAction.setId(templateActionSObject.Id);
		templateAction.setOrder((Integer) templateActionSObject.Order__c);
		templateAction.setType(templateActionSObject.Type__c);
		templateAction.setIsApprovedAction(templateActionSObject.Is_Approved_Action__c);
		templateAction.setActionJSON(templateActionSObject.Action_JSON__c);

		return templateAction;
	}
}